---
- name: Deploy pod to Kubernetes
  hosts: localhost
  gather_facts: false

  vars:
    kubeconfig: /etc/kubernetes/kubelet.conf
    namespace: default
    pod_name: my-pod
    image: nginx:latest

  tasks:
    - name: Create pod definition
      copy:
        content: |
          apiVersion: v1
          kind: Pod
          metadata:
            name: "{{ pod_name }}"
            labels:
              app: nginx
          spec:
            containers:
            - name: nginx
              image: "{{ image }}"
              ports:
              - containerPort: 80

    - name: Create pod
      command: kubectl apply --kubeconfig="{{ kubeconfig }}" -f pod-definition.yaml -n "{{ namespace }}"
